apps:
  - id: example
    name: "example"
    path: "apps/example"
    region: "us-central1"
    artifact_repo: "example"
    secret_prefix: "example"
    secrets: []
  - id: member-onboarding
    name: "member-onboarding"
    path: "apps/member-onboarding"
    region: "us-central1"
    artifact_repo: "member-onboarding"
    secret_prefix: "member-onboarding"
    secrets: []
  - id: certificate-generator
    name: "Certificate-Generator"
    path: "apps/certificate-generator"
    region: "us-central1"
    artifact_repo: "certificate-generator"
    secret_prefix: "certificate-generator"
    secrets: []
