apps:
  - id: example
    name: "example"
    path: "apps/example"
    region: "us-central1"
    artifact_repo: "example"
    secret_prefix: "example"
    secrets: []
  - id: member-onboarding
    name: "member-onboarding"
    path: "apps/member-onboarding"
    region: "us-central1"
    artifact_repo: "member-onboarding"
    secret_prefix: "member-onboarding"
    secrets:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - EMAIL_SENDER
